---
- name: Process list {{ list_item.address }} on {{ pihole_instance.name }}
  block:
    - name: Manage allow list on {{ pihole_instance.name }}
      sbarbett.pihole.allow_list:
        address: "{{ list_item.address }}"
        state: "{{ list_item.state }}"
        comment: "{{ list_item.comment | default(omit) }}"
        groups: "{{ list_item.groups | default([]) }}"
        enabled: "{{ list_item.enabled | default(true) }}"
        url: "{{ pihole_instance.name }}"
        password: "{{ pihole_instance.password }}"
      when: list_item.type == "allow"

    - name: Manage block list on {{ pihole_instance.name }}
      sbarbett.pihole.block_list:
        address: "{{ list_item.address }}"
        state: "{{ list_item.state }}"
        comment: "{{ list_item.comment | default(omit) }}"
        groups: "{{ list_item.groups | default([]) }}"
        enabled: "{{ list_item.enabled | default(true) }}"
        url: "{{ pihole_instance.name }}"
        password: "{{ pihole_instance.password }}"
      when: list_item.type == "block"

    - name: Pause for 1 second
      command: sleep 1
      changed_when: false
      no_log: true 