---
- name: Change the PiHole listening mode
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Change the PiHole listening mode
      sbarbett.pihole.listening_mode:
        # Supported values: "all", "bind", "local" or single
        mode: "all"
        url: "https://your-pihole.example.com"
        password: "{{ pihole_password }}"
