---
- name: Create canonical.example.com CNAME
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create canonical.example.com CNAME
      sbarbett.pihole.local_cname:
        host: canonical.example.com
        target: test.example.com
        ttl: 900
        state: present
        url: "https://your-pihole.example.com"
        password: "{{ pihole_password }}"
