---
- name: Delete test block list
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove a block list
      sbarbett.pihole.block_list:
        address: "https://example.com/blocklist.txt"
        state: absent
        url: "https://your-pihole.example.com"
        password: "{{ pihole_password }}"
