---
- name: Manage Pi-hole groups and clients
  hosts: localhost
  gather_facts: false
  roles:
    - role: sbarbett.pihole.group_client_manager
      vars:
        pihole_hosts:
          - name: "https://your-pihole-1.example.com"
            password: "{{ pihole_password }}"
          - name: "https://your-pihole-2.example.com"
            password: "{{ pihole_password }}"

        pihole_groups:
          - name: Default
            comment: "Default group"
            enabled: true
            state: present
          - name: IOT
            comment: "Internet of Things devices"
            enabled: true
            state: present
          - name: Restricted
            comment: "Restricted access devices"
            enabled: false
            state: present
          - name: OldGroup
            state: absent

        pihole_clients:
          - name: 192.168.1.0/24
            comment: "Main network"
            groups:
              - Default
            state: present
          - name: 192.168.2.0/24
            comment: "IOT network"
            groups:
              - IOT
              - Restricted
            state: present
          - name: 192.168.3.0/24
            state: absent
